- name: Install yum-utils
  yum:
    name: yum-utils
    state: present
- name: Add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python-docker-py']
    state: present

- name: Add ansible_ssh_user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    group: docker
    append: yes

- name: Start docker
  service:
    name: docker
    state: started

- name: Create a network
  docker_network:
    name: network_one
    ipam_config:
      - subnet: 172.3.27.0/24
        gateway: 172.3.27.20
        iprange: 172.3.27.0/26
    appends: yes
